server:
  port: 8084

spring:
  application:
    name: payment-service
  
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:shaik}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}

stripe:
  api-key: ${STRIPE_API_KEY:sk_test_your_stripe_secret_key_here}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:whsec_your_webhook_secret_here}

logging:
  level:
    com.fooddelivery.paymentservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
